### ISSUE TITLE
Enable Flip Intelligently Functionality

### ISSUE THREAD

**Issue by CharoSW** [pratikabu/scrolltotop#132]
The new toolbar button doesn't use the Smart Direction functionality.  Is it possible for that to be implemented or have the ability to scroll to the bottom if the button is clicked and the page is at the top?  Additionally, is it possible for the toolbar icon to show which direction such a click might go?

**Comment by pratikabu** [comment]
I can add "Smart Direction" but I felt it will be confusing.

I did implement the "Flip Intelligently" functionality which does exactly detect when to scroll down/top based on page location. I didn't turn it on because currently it doesn't work when you remove the page icon. I'll try to implement it.

![image](https://user-images.githubusercontent.com/470973/82902592-49dc4480-9f25-11ea-9baa-dc8ced9e6fab.png)

Flipping the icon on the toolbar that frequently might have adverse effect and also require equivalent rotated image to be replaced with. To keep things simple and effective I might not try to implement icon rotation functionality based on the direction. I understand that is not ideal. I'll give it a think later on.

Thanks

**Comment by pratikabu** [comment]
If you currently want the "Flip Intelligently" functionality. Then please run the below javascript in your console window.

`$('.settinggroup div.settinglabel:contains("Click Action :")').parent().show()`

1. Open options page of Scroll To Top
2. Right click on the screen and click "Inspect".
2.1 ![image](https://user-images.githubusercontent.com/470973/82903654-df2c0880-9f26-11ea-9c99-dd09afe58622.png)
3. When the console opens up then go to the "Console" tab.
3.1 ![image](https://user-images.githubusercontent.com/470973/82903746-0682d580-9f27-11ea-855f-479e0a7b2cc2.png)
4. On the textarea paste the code that I've shown above and press enter.
5. You should see a new setting appear on the options page.
![image](https://user-images.githubusercontent.com/470973/82903889-43e76300-9f27-11ea-8de4-d70d6a41cae4.png)

Now you can choose click behavior.

Please note: The "Flip Intelligently" functionality only works when the icon is shown on the page as well.

Cheers

**Comment by pratikabu** [comment]
If it is okay I'll reuse this bug to enable `Flip Intelligently` functionality in the next release? I'll update the title of this bug.

**Comment by CharoSW** [comment]
On further thought you are probably right about smart direction being confusing for the toolbar button but the Flip Intelligently works fine for my purposes so that's all good.  Feel free to change the title of the bug to track that instead

**Comment by pratikabu** [comment]
Completed the changes related to enabling flip intelligently functionality.
