### ISSUE TITLE
Found conflict with Omnibar

### ISSUE THREAD

**Issue by harrison3001** [pratikabu/scrolltotop#32]
Hi, before all thanks for this great extension. Lately, after upgrading to Firefox 33.0.3 I found that the search engine name provided by the Omnibar extension disappeared. After disabling Scroll to Top it has returned. Hope this help.
Andrea

**Comment by pratikabu** [comment]
hi Andrea, seems like firefox is getting many under the hood changes since 33 version, which is causing many things to break.
Anyways talking about this extension, this seems to be a tricky issue as in I've to check which part is causing this issue. Will test it and update my findings on this bug.

Pratik

**Comment by pratikabu** [comment]
Hi Andrea, I'll be closing this issue. Let me know if you've any concerns.
