### ISSUE TITLE
Arrow in toolbar

### ISSUE THREAD

**Issue by iiizio** [pratikabu/scrolltotop#61]
Can you add the option to put the arrow in the toolbar?

**Comment by pratikabu** [comment]
That's a nice and easy to add feature. I might just add a new toolbar button which will take me to the top of the page always.

**Comment by Lew-Rockwell-Fan** [comment]
That would be very nice. One thing about this addon that is superior to any other I know of is the way you make it easy to choose or customise icons. I hope this will be the case for a toolbar button as well. I hate tiny buttons, both because it is hard to distinguish them but because it takes longer to position the pointer JUST RIGHT to click them.

May I suggest an option for a single button that scrolls to the top if you left click it and to the bottom if you right click it?

**Comment by pratikabu** [comment]
hi @iiizio , I know its late but this feature has been implemented with #113 and will be going live with 4.9 release. Thanks

@Lew-Rockwell-Fan, the customized icons will be implemented with #125. I like the right click option. I'll have to analyze whether it will be okay to override browser functionality and create a separate issue later.

Closing this issue.
