### ISSUE TITLE
Save Settings to Google Account

### ISSUE THREAD

**Issue by mickelsonmichael** [pratikabu/scrolltotop#63]
It'd be great if we could save our arrow options to our Google account. Anytime I start a fresh instance of Chrome, the extension is automatically installed but none of my settings are saved.

This would be a very convenient feature, although I don't know how doable it is.

**Comment by pratikabu** [comment]
I've that code ready. I just have to tweak it to migrate old settings.
Will start working on it soon. And yes it is possible to sync your settings.

Regards


On Nov 10, 2017 12:00 PM, "mickelsonmichael" <notifications@github.com>
wrote:

It'd be great if we could save our arrow options to our Google account.
Anytime I start a fresh instance of Chrome, the extension is automatically
installed but none of my settings are saved.

This would be a very convenient feature, although I don't know how doable
it is.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pratikabu/scrolltotop/issues/63>, or mute the thread

**Comment by pratikabu** [comment]
This was already delivered on version 4.7. Closing this issue.
