### ISSUE TITLE
Selected arrow is inconsistent

### ISSUE THREAD

**Issue by ineuw** [pratikabu/scrolltotop#69]
Hi. 
I am not sure where you prefer bug reports, here, or sourceforge?

In any case, I selected one of the recommended double arrows but on some web pages it reverts to the single default arrow. On the other hand, don't feel bad. EVERY Quantum add-on I installed has a bug or two. :-)
P.S: Firefox 57.0.4

**Comment by pratikabu** [comment]
This sounds strange, it shouldn't revert based on web page. I never coded it to behave differently for different pages. Though if Firefox settings are getting messed up then it might happen.

I don't know how can I help here but I've not faced any issue on my Firefox so far.

PS: This is the right place to report bug.

Thanks
Pratik

**Comment by ineuw** [comment]
I wouldn't worry about it. I will keep you updated if I notice anything else. BTW what Firefox settings are you referring to?

**Comment by pratikabu** [comment]
With the latest release of Scroll To Top, I've moved the settings to chrome.storage.sync settings so that it can be synced to all logged in instances. If Firefox is messing with this storage then you might see different behavior. Though as per the documentation it shouldn't mess with it.

I'll close this issue but you can keep commenting on it. Thanks
