### ISSUE TITLE
Not appearing on some pages

### ISSUE THREAD

**Issue by paul1149** [pratikabu/scrolltotop#72]
Hello,

I've been noticing that occasionally STT does not manifest on a page. I just encountered it at https://ask.libreoffice.org/en/question/144785/help-unable-to-download-starts-but-hangs/?answer=144794#post-id-144794

And yet at https://ask.libreoffice.org/en/question/144606/increase-indent-and-tab-stops/ STT works fine.

The first page is in their wiki format, the second isn't. 

This was on vivaldi 1.14, confirmed on slimjet  17.02, both on linux x64.

**Comment by hdd60311** [comment]
I also found that STT doesn't work in some websites, for example: [1](https://www.komica.org/) [2](http://www.andaudio.com/)
Seems that its the same issue with this [discussion](https://github.com/CanisLupus/swift-selection-search/issues/56)?

**Comment by paul1149** [comment]
Maybe, I don't know. But my examples come from the same site, and from the same type of page. This isn't close to a deal-breaker, but I thought I'd report it so the owner could look at it when he has time.

**Comment by pratikabu** [comment]
I didn't check on this yet, though if these sites uses frames then I don't load the addon on frames due to one existing issue where the addon was loading on rich text editors. That had caused lot of issues earlier.
For that reason I load it only at the top level html tag.

I'll take a look at it once I get time to validate if it is same issue.

Thanks
Pratik

**Comment by Caver1** [comment]
I am seeing the same thing.
Two sites that I see this is washingtonpost.com and addons.mozilla.com. There are some others.
Using Firefox61.
Have you had time to look into this yet?
Thank you,
Doug

**Comment by pratikabu** [comment]
I reviewed this issue and found that the urls mentioned by @hdd60311 are all using iFrames and thus this addon won't work there. I only place my addon icon on the top most layer.

Also the links mentioned by @Caver1 are all working fine and the addon does show up there.

The issue mentioned by @paul1149 happens because the addon won't load on a page which doesn't have much to scroll. I only load the addon on pages which have at least something to scroll for.

Closing this issue.
