### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by SoSaysSunny** [pratikabu/scrolltotop#82]
Back before Firefox ruined my wrap-around toolbars layout, I used my right-side toolbar for navigation:

![Firefox 2018-04-16](https://user-images.githubusercontent.com/48607777/54468216-6f35c600-4758-11e9-8544-9c10f842b66b.png)

* ... ~
* Top of page
* Up one screen
* ... ~
* Down one screen
* Bottom of page
* ... ~

It would be nice if you similarly aligned the floating buttons -- especially since a slip of the mouse in your current configuration closes the tab (ack!).

~ Items on my toolbar but not in this Add-On's range of functions:
* (Undo Close Tab, Duplicate Tab, Bookmark all Tabs, Up Directory, Snap Back, First, Previous, Next, Last)
* (Switch to tab on left, Back, Close Tab, Forward, Switch to tab on right)
* (Search Page)

**Comment by pratikabu** [comment]
Hi @SoSaysSunny, Chrome and Firefox are moving towards single responsibility of an extension. The extension can have only clear purpose otherwise they will reject the upgrade. So I can't add tab manipulation related buttons.

Regarding the button placements, in my recent release 4.8.5, I gave an extra option to remove the close button. Kindly check that let me know if that works for you.

**Comment by pratikabu** [comment]
Closing this issue.
